### ISSUE TITLE
Add method to be able to set custom bubble style in ChipEditText 

### ISSUE THREAD

**Issue by biokys** [eyeem/chips-android#12]
Now it s not possible to change the default style and in my layout, where the text is black and background is white, the ChipEditText is useless. :-(

**Comment by wonsuc** [comment]
There's several options with "DefaultBubbles" class.

```java
public static int LILA = 0;
public static int GRAY = 1;
public static int GRAY_WHITE_TEXT = 2;
public static int GREY_EDIT = 3;
public static int GREEN = 4;
public static int CITY_COUNTRY = 5;
```

or u can try "AwesomeBubble" class, I never tried.

plus, I just edited original source and It is not that hard to adapt custom style to the Bubbles.

**Comment by vishna** [comment]
@biokys I agree, I will try to find more time to make ChipEditText more customizable and also configurable through xml.
