### ISSUE TITLE
ChipsTextView rendering in List adapter

### ISSUE THREAD

**Issue by sohayb** [eyeem/chips-android#16]
Hello,
It seems there's a problem in rendering bubbles in ChipsTextView in a list item view when the list is first displayed, when I scroll, all new items and the old ones are rendered correctly.
Is there a workaround for this?

Thank you

**Comment by syrakozz** [comment]
+1

**Comment by vishna** [comment]
I've just rewrote the sample app dramatically so please check it out for the reference.

The main change allows text rendering in the background which improves the scrolling performance. This method is now preferred.

Nonetheless, the old api should be working, I might have broken something in the process so I will look more deep into that issue tomorrow.

**Comment by sohayb** [comment]
thanks a lot :)
